### ISSUE TITLE
Add a Stylus Version ?

### ISSUE THREAD

**Issue by johngerome** [ianrose/typesettings#23]
Hello @ianrose ,

Can i make a stylus version of this ? cause i didn't see any of it. I would love to convert this one and it's gonna be a big help on a stylus user. 
Thank You.

**Comment by johngerome** [comment]
Done @ianrose I created a new file instead of replacing it #27

**Comment by ianrose** [comment]
@johngerome nice, :+1:  I'll check it out and merge
