### ISSUE TITLE
Good vertical rhythm

### ISSUE THREAD

**Issue by admdh** [ianrose/typesettings#35]
How good vertical rhythm look likes based on this settings? i have tried to use another font-faces and could figure out and configure to look good. and for example where should margin be before red line (debug grid) or outside?

**Comment by ianrose** [comment]
@admdh good questions. Each typeface will have different characteristics that affect line-height, size, and line length. The default settings should be treated as a good starting point and I encourage you to tinker with them as a designer to find the right sweet spot. 

As for the margin example if you use the `emRhythm` function the margin should be a multiple of your base vertical unit https://github.com/ianrose/typesettings/blob/master/_typesettings.scss#L37. The base vertical unit value is used to create the `body` baseline. So often there will be times when it will not land directly on the debug grid.

A good read on the topic: http://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly/
