### ISSUE TITLE
Is it possible to change the scale ratio

### ISSUE THREAD

**Issue by Madebym** [ianrose/typesettings#38]
I am trying to change the scale ratio to a different one than 1.414. But providing other modular scale ratios doesn't have any effect on the outputed CSS.

It always outputs the values used by the default ratio. If I change base font size for example, I can see the changes, so it is not due to some compile error on my side.

Am I missing something obvious?

**Comment by ianrose** [comment]
@Madebym I put the latest release of `_typesetting.scss` into this Codpen: http://codepen.io/ianrose/pen/JYRoGL

Check out line `4` of the CSS (SCSS). The Pen looks to be working as expected. Where are you setting the new `$ms-ratio` in your project? Could be an issue of when `_typsettings.scss` is being imported and where `$ms-ratio` is being set. Also make sure you are using the `$ms-` vars for setting font-size. For example  `font-size: $ms-up1;`, `font-size: $ms-down1;`, or the `@include setType(6, $ms-up2);`.

Please let me know if you are still having issues or see a problem with the Pen. Also happy to look at a repo or gist.

**Comment by Madebym** [comment]
@ianrose I want to apologize for wasting your time with setting up a codepen. It was a beginner mistake from my side, I was changing the default `$ms-ratio` variable, not knowing that it basically means "unless this is already assigned".

Thanks for the quick help!
