### ISSUE TITLE
Make a NPM package

### ISSUE THREAD

**Issue by ianrose** [ianrose/typesettings#39]
related #2

**Comment by ianrose** [comment]
@onemanstartup https://www.npmjs.com/package/typesettings

**Comment by onemanstartup** [comment]
@ianrose thanks!

**Comment by Lighttree** [comment]
Hi there! It seems that NPM package doesn't work properly. It fails when try to require typesettings.
https://tonicdev.com/npm/typesettings

**Comment by ianrose** [comment]
@Lighttree can you elaborate the use case for including Typsettings in a project this way?

**Comment by sidelsky** [comment]
Just testing it out - seeing if it worth using in my next
project...why'd you ask?
 

----- Original Message -----

**Comment by Lighttree** [comment]
@ianrose I've discovered this way of importing yesterday from [bourbon npm install.](https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline) to be honest :)

```
'use strict';

var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var bourbon = require('bourbon');
var input = 'src/assets/styles/**/*.scss';
var devOutput = '.tmp/assets/styles';
var prodOutput = 'dist/assets/styles';
var sassOptions = {
    includePaths: [bourbon.includePaths],
    errLogToConsole: true,
    outputStyle: 'expanded'
};
var sourcemapsOptions = {
    includeContent: false,
    sourceRoot: './' // use the file's folder as source root
};

gulp.task('styles', function () {
    return gulp
        // Find all `.scss` files from the `stylesheets/` folder
        .src(input)
        .pipe($.sourcemaps.init())
        // Run Sass on those files
        .pipe($.sass(sassOptions).on('error', $.sass.logError))
        .pipe($.sourcemaps.write(sourcemapsOptions))
        // Write dev version of CSS in the output folder
        .pipe(gulp.dest(devOutput))
        // Write prod version of CSS in output folder
        .pipe($.if('*.css', $.csso()))
        .pipe(gulp.dest(prodOutput))
        .pipe($.size({title: 'styles'}));
});
```

`bourbon.includePath` allows resolve naming issue and import bourbon as `@import "bourbon";`

I was thinking that this is some kind of agreement that NPM modules should export such API. But probably not :)
