### ISSUE TITLE
Either indent or space, not both

### ISSUE THREAD

**Issue by Hambern** [ianrose/typesettings#41]
First of all... thanks a lot for this. But could you let us choose weither to divide paragraphs inte EITHER space OR indentation. Both of these are typographically correct. But to use both of them at the same time is not. :) Could you put this logic into the library?

**Comment by ianrose** [comment]
@Hambern thanks for using Typesettings. By default it will indent paragraphs that are siblings and set a negative margin top that is equal to the default margin bottom. This results in sibling paragraphs separated only by indent and allows other elements like images to be separated below body text by a rhythm based margin. Please take a look at the following CodePen. 

**CodePen Example:**
http://codepen.io/ianrose/pen/RGgxPB

**The SCSS Ruleset:**
https://github.com/ianrose/typesettings/blob/master/_typesettings.scss#L321-L326

Let me know if this answers your question.
