### ISSUE TITLE
not getting nice results in multi line headings

### ISSUE THREAD

**Issue by ianhobbs** [ianrose/typesettings#46]
After following the regular set up...
settings:

$font-sans: $myBod
$font-serif: $Archer
$font-mono: 'Lucida Console', Monaco, monospace
$text-color: #000
$base-vertical-unit: 6.1px
$base-line-multi: 4
$base-font-size: 18px
$ms-ratio: 1.51
$paragraph-indent: true
$paragraph-justify: true
$load-typesetted: true

Looks great on the paragraph font but not on the multi line headings...
working through a solution now.
see a sample here.

http://rejmyre.codey.hosting/style.php
Thanks Ian

**Comment by ianrose** [comment]
Hi @ianhobbs when inspecting your style guide I'm seeing a computed a line-height for `<p>` of `25.9999px` when I'm expecting to see `6.1 * 4 = 24.4px`. What version of typesettings are you using?

**Comment by ianhobbs** [comment]
4.0.0
The url has changed to http://rejmyre.codeyhosting.net/style

**Comment by ianrose** [comment]
@ianhobbs looking at your source:

```sass
$font-sans: $myBod
$font-serif: $Archer
$font-mono: 'Lucida Console', Monaco, monospace
$text-color: #000
$base-vertical-unit: 6.5px
$base-line-multi: 4
$base-font-size: 18px
$ms-ratio: 1.51
$paragraph-indent: true
$paragraph-justify: true
$load-typesetted: true
```
The computed values look correct. What is causing the visual issues are your `ms-ratio` and the `base-font-size` values. The font-sizes are "scaling up to quickly" for the vertical multipliers that `_typesetted.scss` defaults too on the headings.

Below I'm running your config with OpenSans in the `typesettings` tests.

![image](https://user-images.githubusercontent.com/952321/29873708-431601ea-8d62-11e7-9e45-d414abce4931.png)

If I change the `ms-ratio` to a value that doesn't scale up as quickly, `1.414`, while keeping your desired `base-vertical-unit` of `6.5px`:

![image](https://user-images.githubusercontent.com/952321/29873753-6e79bf48-8d62-11e7-832e-514dc150c812.png)

Another approach, keep the `ms-ratio` of `1.51` increase your `base-vertical-unit` to an even `8px` and bump down your `base-line-multi` to `3`:

![image](https://user-images.githubusercontent.com/952321/29873831-c60471a4-8d62-11e7-902a-8dc6bc447124.png)

Another option is to set `$load-typesetted: false` and write custom styles using `typesettings` function and mixins (I often do this). https://github.com/ianrose/ianrose.me/blob/master/src/styles/_config.scss#L16-L42 and https://github.com/ianrose/ianrose.me/blob/master/src/styles/base/_base.scss
